### PR TITLE
Combine cygwin, freebsd, linux(64), macos and rtems ports into one

### PR DESCRIPTION
**Pull request by jrtc27**
These are almost entirely identical; instead of copying the same hundreds of lines around for every new POSIX-like port, provide a default "posix" port that each then inherits from and overrides accordingly.

Note that this also removes the pointless linux64 port, leaving just linux for any OS-specific overrides (currently none).

This also now sets PORT_DIR automatically on macOS and FreeBSD.

Tested on macOS, FreeBSD and Linux (64-bit).

### CODE REVIEW

**Comment by petertorelli** [comment]
@jrtc27,

This is a great idea. Thanks for taking the time to consolidate. We'll schedule review and testing on our side.

Thanks,
Peter

**Comment by petertorelli** [comment]
Merging into a branch, need to do a bit more testing.

**Comment by petertorelli** [comment]
@jrtc27 -- This doesn't configure HAS_CLOCK correctly under RTEMS as it doesn't include the overrides file if PORT_DIR=rtems. I don't have an RTEMS machine but I found it wasn't using the proper include. Would be great if you could fix that bug and test? Thanks.

**Comment by jrtc27** [comment]
> @jrtc27 -- This doesn't configure HAS_CLOCK correctly under RTEMS as it doesn't include the overrides file if PORT_DIR=rtems. I don't have an RTEMS machine but I found it wasn't using the proper include. Would be great if you could fix that bug and test? Thanks.

So, that was deliberate, because RTEMS's documentation says the functions/types/constants _do_ exist, and there was no explanation for why the RTEMS port overrode it. @heshamelmatary was there a reason for it?

**Comment by heshamelmatary** [comment]
`USE_CLOCK` can be 0 for RTEMS and it can just use `time.h`

There are a few issues with the RTEMS port though. POSIX on RTEMS is optional, so we still want to build CoreMark without it.

The other thing is that CoreMark is being built as an RTEMS application, which requires an `Init` task/function to be defined along with some config defines and includes [1]. The RTEMS kernel and CoreMark app (being an embedded RTOS) are statically linked into a single ELF.

[1] https://github.com/eembc/coremark/blob/main/rtems/core_portme.c#L342...L364

**Pull request merged**
